### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by g3ortega** [mattmueller/foursquare2#104]
Hi @mattfawcett, first of all, thanks for your work with this Gem.

I would like to know the current status.

We'll be using a lot Foursquare API. I already upgrade all the dependencies of the Gem and solved an annoying issue with Hashie logs, with all tests green.

I wanted to know if you're receiving pull requests, or if I can create and maintain a separate Gem and also address other issues.

Thanks in advance,

**Comment by mattmueller** [comment]
Hey @g3ortega -

I no longer have time to maintain this gem. If you would like to take over maintenance (or know someone who would), I am happy to transfer ownership. Otherwise I think a fork is probably your best option.

**Comment by g3ortega** [comment]
Hi @mattmueller, thanks for your response, 

I'm willing to maintain this gem, also we are going to be using Foursquare APIs a lot in my company, so other people of the team would be helping if needed.

**Comment by mattmueller** [comment]
That's great @g3ortega ! Would you prefer me to simply add you (and anyone else from your team) as collaborators or transfer the actual repo to your account?

**Comment by g3ortega** [comment]
Hi @mattmueller, what you think it's best for you. For now for now only I'll be actively contributing from my team.

**Comment by mattmueller** [comment]
@g3ortega I've invited you as a collaborator. Closing this out for now.
