### ISSUE TITLE
Retreiving Menus

### ISSUE THREAD

**Issue by OShalaby** [mattmueller/foursquare2#72]
Hi,
Nice gem, I noticed in the full list of methods, there's none to call a menu i.e. "client.venue.menu", what I'm trying to achieve is:
https://developer.foursquare.com/docs/explore#req=venues/47a1bddbf964a5207a4d1fe3/menu

**Comment by g3ortega** [comment]
Closing this issue we already have this endpoint (https://developer.foursquare.com/docs/api/venues/menu) covered, you can check it for more details:

https://github.com/mattmueller/foursquare2/blob/0affc7d4bd5a3aea51e16782def38f589d16e60a/lib/foursquare2/venues.rb#L219
