### ISSUE TITLE
Bundler could not find compatible versions for gem "faraday"

### ISSUE THREAD

**Issue by troshchenko** [mattmueller/foursquare2#77]
I've got the following error with the "bundler outdated" command: 

Updating git://github.com/rweng/jquery-datatables-rails.git
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...

Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    foursquare2 (~> 1.9.8) ruby depends on
      faraday (< 0.9, >= 0.7.4) ruby

```
foursquare2 (~> 1.9.8) ruby depends on
  faraday (0.9.0)
```

**Comment by g3ortega** [comment]
The current version dependencies are working well for most of the cases, for the next version Faraday and other dependencies will be updated to keep it aligned with the new releases of major projects as Rails and their versions of dependencies.
