### ISSUE TITLE
Venues/Explore Endpoint?

### ISSUE THREAD

**Issue by dmastylo** [mattmueller/foursquare2#88]
Looks like this endpoint is missing unless I'm missing something

https://developer.foursquare.com/docs/venues/explore

**Comment by daltonrenaldo** [comment]
seems like it

**Comment by g3ortega** [comment]
This endpoint is already covered 
https://github.com/mattmueller/foursquare2/blob/0affc7d4bd5a3aea51e16782def38f589d16e60a/lib/foursquare2/venues.rb#L191
