### ISSUE TITLE
Search venue by name

### ISSUE THREAD

**Issue by cyzanfar** [mattmueller/foursquare2#96]
When I query the foursquare API for lets say a restaurant :  

```
foursquare_client.search_venues(:ll => '40.712784,-74.005941', :query => 'antica pesa')
```

I am unable to get the ratings for that particular place. Is there any way to get that information?

**Comment by DeProdigy** [comment]
@cyzanfar I belive you need to query each venue separately for the rating. [This is the response when you search venues](https://developer.foursquare.com/docs/explore#req=venues/search%3Fll%3D40.7,-74), it's a collection of venues and [this is a query for an individual venue](https://developer.foursquare.com/docs/explore#req=venues/40a55d80f964a52020f31ee3). As you see, there are no ratings in the "collection" response.
