### ISSUE TITLE
The Foursquare API no longer supports requests that do not pass in a version parameter.

### ISSUE THREAD

**Issue by beeksiwaais** [mattmueller/foursquare2#97]
Hi, 

I get 'The Foursquare API no longer supports requests that do not pass in a version parameter'
then 'The Foursquare API no longer supports requests that pass in a version v ...' when I use your exemple in the README.

Any idea ?

**Comment by DeProdigy** [comment]
@beeksiwaais when you're initializing the client, add the `api_version` parameters as part of the `new` method's parameters: [Docs](https://github.com/mattmueller/foursquare2#instantiate-a-client-with-versioning)
