### ISSUE TITLE
search_venues does not support NE + SW paramaters

### ISSUE THREAD

**Issue by DeProdigy** [mattmueller/foursquare2#98]
I was looking into querying the venues based on the quadrangle defined by the latitude and longitude. [Foursquare API supports such queries](https://developer.foursquare.com/docs/venues/search). I wanted to find out if the gem does or will support those queries as well. Thanks.

**Comment by mattmueller** [comment]
All methods should support passing any additional parameters. So if I'm understanding you correctly I believe this would look something like:

```
client.search_venues(intent: 'browse', ne: '44.1,37.4', sw: '44.3,37.2')
```

Is that not working for you?

**Comment by DeProdigy** [comment]
@mattmueller did not not about the `intent` parameter.
That's the exact solution I was looking for. Thank you!
